
var Verbs : Array := Array(18) as Array;
Verbs.Set(0, 'GO ');
Verbs.Set(1, 'GET');
Verbs.Set(2, 'DRO');
Verbs.Set(3, 'PUS');
Verbs.Set(4, 'PUL');
Verbs.Set(5, 'LOO');
Verbs.Set(6, 'INS');
Verbs.Set(7, 'OPE');
Verbs.Set(8, 'WEA');
Verbs.Set(9, 'REA');
Verbs.Set(10, 'STA');
Verbs.Set(11, 'BRE');
Verbs.Set(12, 'CUT');
Verbs.Set(13, 'THR');
Verbs.Set(14, 'CON');
Verbs.Set(15, 'QUI');
Verbs.Set(16, 'BON');
Verbs.Set(17, 'INV');